networks:
  dockernetwork:
    external: true
services:
  pi-hole:
    image: pihole/pihole:latest
    hostname: pi-hole
    container_name: pi-hole
    # Adding security option to prevent new privileges from being granted
    security_opt:
      - no-new-privileges:true
    networks:
      dockernetwork:
        ipv4_address: 172.28.1.97
    ports:
      - "8081:80/tcp" # Pi-hole web admin interface, proxied through Caddy (configure port in Caddyfile)
      - "53:53/udp"
      - "53:53/tcp"
      # - "67:67/udp" # DHCP, if desired. If not bound to host net you need an mDNS proxy service configured somewhere on host net.
        # ref: https://docs.pi-hole.net/docker/DHCP/
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: 'Asia/Kolkata'
      FTLCONF_webserver_api_password: $PIHOLE_PWD
    volumes:
      - './etc-pihole:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most.
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    # cap_add:
      # - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped